/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jgui;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author blackzafiro
 */
public class Calculadora extends javax.swing.JFrame {
    
    @FunctionalInterface
    private interface OperaciónBinaria {
        public double opera(double n1, double n2);
    }
    
    private enum Operación {
        multiplicación,
        suma,
        resta,
        división;
        
        javax.swing.JButton jButton;
        OperaciónBinaria operación;
        
        void setAttributes(javax.swing.JButton jButton, OperaciónBinaria op) {
            this.jButton = jButton;
            this.operación = op;
        }
    }
    
    /* La calculadora procesa y almacena datos en fases. */
    private enum Fase {
        cero,  // Cero inicial
        uno,   // Introducción del primer operando
        dos    // Introducción del segundo operando, o posteriores.
    }
    
    /* Mostrar en pantalla o el usuario está escribiendo. */
    private enum FasePantalla {
        mostrar,  // Se está mostrando un resultado en pantalla
        escribir  // El usuario está escribiendo números.
    }
    
    private Operación operación = null;
    private double valorAcumulado = 0;
    private Fase fase = Fase.cero;
    private FasePantalla fasePantalla = FasePantalla.mostrar;
    private Color opColor;
    private boolean equalIsOn = false;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        opColor = this.jButton0.getBackground();
        Operación.división.setAttributes(this.jButtonDiv, (n1, n2) -> n1/n2);
        Operación.multiplicación.setAttributes(this.jButtonMult, (n1, n2) -> n1*n2);
        Operación.resta.setAttributes(this.jButtonMinus, (n1, n2) -> n1-n2);
        Operación.suma.setAttributes(this.jButtonPlus, (n1, n2) -> n1+n2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonPercentage = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonAC = new javax.swing.JButton();
        panelPantalla = new javax.swing.JScrollPane();
        textoPantalla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new java.awt.GridBagLayout());

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel.add(jButton7, new java.awt.GridBagConstraints());

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel.add(jButton8, new java.awt.GridBagConstraints());

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel.add(jButton9, new java.awt.GridBagConstraints());

        jButtonDiv.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel.add(jButtonDiv, gridBagConstraints);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel.add(jButton4, gridBagConstraints);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel.add(jButton5, gridBagConstraints);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel.add(jButton6, gridBagConstraints);

        jButtonMult.setText("*");
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel.add(jButtonMult, gridBagConstraints);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel.add(jButton1, gridBagConstraints);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel.add(jButton2, gridBagConstraints);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel.add(jButton3, gridBagConstraints);

        jButtonMinus.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel.add(jButtonMinus, gridBagConstraints);

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel.add(jButton0, gridBagConstraints);

        jButtonDot.setText(".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel.add(jButtonDot, gridBagConstraints);

        jButtonPercentage.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel.add(jButtonPercentage, gridBagConstraints);

        jButtonPlus.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel.add(jButtonPlus, gridBagConstraints);

        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel.add(jButtonEqual, gridBagConstraints);

        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        jPanel.add(jButtonC, new java.awt.GridBagConstraints());

        jButtonAC.setText("AC");
        jButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACActionPerformed(evt);
            }
        });
        jPanel.add(jButtonAC, new java.awt.GridBagConstraints());

        panelPantalla.setBackground(new java.awt.Color(234, 234, 234));
        panelPantalla.setForeground(new java.awt.Color(33, 33, 33));

        textoPantalla.setEditable(false);
        textoPantalla.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textoPantalla.setText("0");
        panelPantalla.setViewportView(textoPantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPantalla, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButtonNumber(evt, jButton7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButtonNumber(evt, jButton4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        textoPantalla.setText("0");
        if (equalIsOn) {
            this.jButtonEqual.setBackground(opColor);
            this.equalIsOn = false;
        }
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButtonNumber(evt, jButton8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButtonNumber(evt, jButton9);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButtonNumber(evt, jButton5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButtonNumber(evt, jButton6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButtonNumber(evt, jButton1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButtonNumber(evt, jButton2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButtonNumber(evt, jButton3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        if (!textoPantalla.getText().equals("0")) {
            textoPantalla.setText(textoPantalla.getText() + jButton0.getText());
        }
        if (equalIsOn) {
            this.jButtonEqual.setBackground(opColor);
            this.equalIsOn = false;
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACActionPerformed
        valorAcumulado = 0;
        textoPantalla.setText("0");
        fase = Fase.cero;
        fasePantalla = FasePantalla.mostrar;
        if (operación != null) {
            operación.jButton.setBackground(opColor);
            operación = null;
        }
        if (equalIsOn) {
            this.jButtonEqual.setBackground(opColor);
            this.equalIsOn = false;
        }
    }//GEN-LAST:event_jButtonACActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        double valor = Double.parseDouble(textoPantalla.getText());
        // 2 a 3
        if(fase == Fase.uno) {
            operación = Operación.multiplicación;
            valorAcumulado = valor;
            fase = Fase.dos;
            fasePantalla = FasePantalla.mostrar;
            textoPantalla.setText(Double.toString(valorAcumulado));
            blink(jButtonMult);
            // 6 a 3
            if (equalIsOn) {
                this.jButtonEqual.setBackground(opColor);
                this.equalIsOn = false;
            }
        }
        // 4 a 7
        else if (fase == Fase.dos && fasePantalla == FasePantalla.escribir) {
            valorAcumulado = operación.operación.opera(valorAcumulado, valor);
            operación = Operación.multiplicación;
            fase = Fase.uno;
            fasePantalla = FasePantalla.mostrar;
            textoPantalla.setText(Double.toString(valorAcumulado));
        }
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // 2 a 6
        if (operación == null && valorAcumulado == 0) {
            double valor = Double.parseDouble(textoPantalla.getText());
            valorAcumulado = valor;
            fase = Fase.uno;
            blink(jButtonEqual); equalIsOn = true;
            fasePantalla = FasePantalla.mostrar;
            textoPantalla.setText(Double.toString(valorAcumulado));
        } // 6 a 2
        else if(operación == null && valorAcumulado != 0) {
            valorAcumulado = 0;
            fase = Fase.uno;
            blink(jButtonEqual); equalIsOn = true;
            fasePantalla = FasePantalla.escribir;
        } // 3 a 8, 7 a 6
        else if(fase == Fase.dos && fasePantalla == FasePantalla.mostrar) {
            fase = Fase.uno;
            operación.jButton.setBackground(opColor); operación = null;
            blink(jButtonEqual); equalIsOn = true;
        } // 4 a 5
        else if(fase == Fase.dos && fasePantalla == FasePantalla.escribir) {
            double valor = Double.parseDouble(textoPantalla.getText());
            valorAcumulado = operación.operación.opera(valorAcumulado, valor);
            operación = null;
            fasePantalla = FasePantalla.mostrar;
            textoPantalla.setText(Double.toString(valorAcumulado));
            fase = Fase.uno;
            blink(jButtonEqual); equalIsOn = true;
        }
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonNumber(java.awt.event.ActionEvent evt, javax.swing.JButton jButton) {
        if (textoPantalla.getText().equals("0") || fasePantalla == FasePantalla.mostrar) {
            textoPantalla.setText(jButton.getText());
            fasePantalla = FasePantalla.escribir;
            if (operación != null) {
                operación.jButton.setBackground(opColor);
            }
            if (fase == Fase.cero) fase = Fase.uno;
            else if (fase == Fase.uno && operación != null) {
                fase = Fase.dos;
            }
            // 6 a 2
            else if (fase == Fase.uno && operación == null) {
                valorAcumulado = 0;
                fasePantalla = FasePantalla.escribir;
            }
        } else {
            textoPantalla.setText(textoPantalla.getText() + jButton.getText());
        }
        
        if (equalIsOn) {
            this.jButtonEqual.setBackground(opColor);
            this.equalIsOn = false;
        }
    }
    
    /* Hace parpadear la pantalla. */
    private void blink(JButton jButton) {
        jButton.setBackground(Color.magenta);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAC;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPercentage;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane panelPantalla;
    private javax.swing.JTextField textoPantalla;
    // End of variables declaration//GEN-END:variables
}
